# https://www.docker.elastic.co/
FROM grafana/grafana

# Add your grafana plugins setup here
# Example: RUN ./bin/grafana-cli plugins install grafana-worldmap-panel
RUN ./bin/grafana-cli plugins install grafana-worldmap-panel

RUN ./bin/grafana-cli plugins install grafana-piechart-panel

